//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import org.apache.abdera.factory.Factory;
import org.apache.abdera.model.Element;
import org.apache.abdera.model.ExtensibleElement;
import org.opencare.lib.model.BaseWrapper;


/**
 * Complex type that defines the name of the country and is reused in other CIQ specs
 * 
 * <p>Java class for CountryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CountryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NameElement" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:oasis:names:tc:ciq:xal:3>NameType">
 *                 &lt;attribute name="NameType" type="{urn:oasis:names:tc:ciq:xal:3}CountryNameTypeList" />
 *                 &lt;attribute name="NameCode" type="{urn:oasis:names:tc:ciq:xal:3}CountryNameCodeList" />
 *                 &lt;attribute name="NameCodeType" type="{urn:oasis:names:tc:ciq:ct:3}String" />
 *                 &lt;anyAttribute processContents='lax' namespace='##other'/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CountryType", namespace = "urn:oasis:names:tc:ciq:xal:3", propOrder = {
    "nameElement"
})
//@XmlSeeAlso({
//    org.mitre.eren.protocol.edxl_rm.Nationalities.Country.class,
//    org.mitre.eren.protocol.edxl_rm.CountriesOfResidence.Country.class,
//    org.mitre.eren.protocol.edxl_rm.AddressType.Country.class
//})
public class CountryType extends BaseWrapper implements Element, ExtensibleElement, EDXLRMConstants {

    public CountryType(Element internal) {
    super(internal);
    // TODO Auto-generated constructor stub
  }

  public CountryType(Factory factory, QName qname) {
    super(factory, qname);
    // TODO Auto-generated constructor stub
  }


    @XmlElement(name = "NameElement", required = true)
    protected List<CountryType.NameElement> nameElement;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the nameElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountryType.NameElement }
     * 
     * 
     */
    public List<CountryType.NameElement> getNameElement() {
        if (nameElement == null) {
            nameElement = new ArrayList<CountryType.NameElement>();
        }
        return this.nameElement;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:oasis:names:tc:ciq:xal:3>NameType">
     *       &lt;attribute name="NameType" type="{urn:oasis:names:tc:ciq:xal:3}CountryNameTypeList" />
     *       &lt;attribute name="NameCode" type="{urn:oasis:names:tc:ciq:xal:3}CountryNameCodeList" />
     *       &lt;attribute name="NameCodeType" type="{urn:oasis:names:tc:ciq:ct:3}String" />
     *       &lt;anyAttribute processContents='lax' namespace='##other'/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NameElement
        extends NameType
    {

        @XmlAttribute(name = "NameType", namespace = "urn:oasis:names:tc:ciq:xal:3")
        protected CountryNameTypeList nameType;
        @XmlAttribute(name = "NameCode", namespace = "urn:oasis:names:tc:ciq:xal:3")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String nameCode;
        @XmlAttribute(name = "NameCodeType", namespace = "urn:oasis:names:tc:ciq:xal:3")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String nameCodeType;

        /**
         * Gets the value of the nameType property.
         * 
         * @return
         *     possible object is
         *     {@link CountryNameTypeList }
         *     
         */
        public CountryNameTypeList getNameType() {
            return nameType;
        }

        /**
         * Sets the value of the nameType property.
         * 
         * @param value
         *     allowed object is
         *     {@link CountryNameTypeList }
         *     
         */
        public void setNameType(CountryNameTypeList value) {
            this.nameType = value;
        }

        /**
         * Gets the value of the nameCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameCode() {
            return nameCode;
        }

        /**
         * Sets the value of the nameCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameCode(String value) {
            this.nameCode = value;
        }

        /**
         * Gets the value of the nameCodeType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameCodeType() {
            return nameCodeType;
        }

        /**
         * Sets the value of the nameCodeType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameCodeType(String value) {
            this.nameCodeType = value;
        }

    }

}
