//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DirectionTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DirectionTypeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="East"/>
 *     &lt;enumeration value="West"/>
 *     &lt;enumeration value="North"/>
 *     &lt;enumeration value="South"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DirectionTypeList", namespace = "urn:oasis:names:tc:ciq:xal:3")
@XmlEnum
public enum DirectionTypeList {

    @XmlEnumValue("East")
    EAST("East"),
    @XmlEnumValue("West")
    WEST("West"),
    @XmlEnumValue("North")
    NORTH("North"),
    @XmlEnumValue("South")
    SOUTH("South");
    private final String value;

    DirectionTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DirectionTypeList fromValue(String v) {
        for (DirectionTypeList c: DirectionTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
