//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeatureTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FeatureTypeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Weight"/>
 *     &lt;enumeration value="Height"/>
 *     &lt;enumeration value="HairColour"/>
 *     &lt;enumeration value="EyeColour"/>
 *     &lt;enumeration value="SkinColour"/>
 *     &lt;enumeration value="Waist"/>
 *     &lt;enumeration value="Breast"/>
 *     &lt;enumeration value="Hip"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FeatureTypeList")
@XmlEnum
public enum FeatureTypeList {

    @XmlEnumValue("Weight")
    WEIGHT("Weight"),
    @XmlEnumValue("Height")
    HEIGHT("Height"),
    @XmlEnumValue("HairColour")
    HAIR_COLOUR("HairColour"),
    @XmlEnumValue("EyeColour")
    EYE_COLOUR("EyeColour"),
    @XmlEnumValue("SkinColour")
    SKIN_COLOUR("SkinColour"),
    @XmlEnumValue("Waist")
    WAIST("Waist"),
    @XmlEnumValue("Breast")
    BREAST("Breast"),
    @XmlEnumValue("Hip")
    HIP("Hip");
    private final String value;

    FeatureTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FeatureTypeList fromValue(String v) {
        for (FeatureTypeList c: FeatureTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
