//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdentifierElementTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IdentifierElementTypeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Name"/>
 *     &lt;enumeration value="RangeFrom"/>
 *     &lt;enumeration value="Range"/>
 *     &lt;enumeration value="RangeTo"/>
 *     &lt;enumeration value="Prefix"/>
 *     &lt;enumeration value="Suffix"/>
 *     &lt;enumeration value="Number"/>
 *     &lt;enumeration value="Separator"/>
 *     &lt;enumeration value="Extension"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IdentifierElementTypeList", namespace = "urn:oasis:names:tc:ciq:xal:3")
@XmlEnum
public enum IdentifierElementTypeList {


    /**
     * Applicable to mail box office names such as PO BOX, GPO BOX, MAIL BAG NO., etc. 
     * 
     */
    @XmlEnumValue("Name")
    NAME("Name"),

    /**
     * Indicates that the element contains the lower value of a range, e.g. 25 in 25-37
     * 
     */
    @XmlEnumValue("RangeFrom")
    RANGE_FROM("RangeFrom"),

    /**
     * Indicates that the value is a range, e.g. 25-37
     * 
     */
    @XmlEnumValue("Range")
    RANGE("Range"),

    /**
     * Indicates that the element contains the top value of a range, e.g. 25 in 25-37
     * 
     */
    @XmlEnumValue("RangeTo")
    RANGE_TO("RangeTo"),

    /**
     * Indocates that the element contains some value that is important, but not exactly the number itself. E.g. PoBox can be a prefix in PoBox 2020, street no. A-15, where A is the prefix and 15 is the number
     * 
     */
    @XmlEnumValue("Prefix")
    PREFIX("Prefix"),

    /**
     * Indicates that the element contains some value that is important, but not exactly the number itself. E.g. 'bis' in '45 bis'
     * 
     */
    @XmlEnumValue("Suffix")
    SUFFIX("Suffix"),

    /**
     * Indicates that the value is number, e.g. 2020 in PoBox 2020. The actual value can be alpha-numeric. 
     * 
     */
    @XmlEnumValue("Number")
    NUMBER("Number"),

    /**
     * Indicates that the value is a separator that is expected to be preserved. Examples are / - #, as in 15-A where "-" is the separator
     * 
     */
    @XmlEnumValue("Separator")
    SEPARATOR("Separator"),

    /**
     * Indicates that the value is an extension number of some identifier, e.g. 01 in Private Bag 2330-01, where the main number of the private bag is 2330, 12345-1223 in post code where 1223 is the extension
     * 
     */
    @XmlEnumValue("Extension")
    EXTENSION("Extension");
    private final String value;

    IdentifierElementTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdentifierElementTypeList fromValue(String v) {
        for (IdentifierElementTypeList c: IdentifierElementTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
