//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

import org.apache.abdera.factory.Factory;
import org.apache.abdera.model.Element;
import org.opencare.lib.model.BaseWrapper;


/**
 * <p>Java class for LocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LocationDescription" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}LocationDescriptionType" minOccurs="0"/>
 *         &lt;element name="Address" type="{urn:oasis:names:tc:ciq:xal:3}AddressType" minOccurs="0"/>
 *         &lt;element name="TargetArea" type="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0:geo-oasis}WhereType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationType", namespace = "urn:oasis:names:tc:emergency:EDXL:RM:1.0", propOrder = {
    "locationDescription",
    "address",
    "targetArea"
})
public class LocationTypeWrapper extends BaseWrapper implements LocationType {

    public LocationTypeWrapper(Element internal) {
    super(internal);
    // TODO Auto-generated constructor stub
  }

  public LocationTypeWrapper(Factory factory, QName qname) {
    super(factory, qname);
    // TODO Auto-generated constructor stub
  }


    /**
     * Gets the value of the locationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getLocationDescription() {
      return getSimpleExtension(RM_LOCATIONDESCRIPTION);
    }

    /**
     * Sets the value of the locationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setLocationDescription(String value) {
        setElementText(RM_LOCATIONDESCRIPTION,value);
    }
//
//    /**
//     * Gets the value of the address property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link AddressType }
//     *     
//     */
//    public AddressType getAddress() {
//        return address;
//    }
//
//    /**
//     * Sets the value of the address property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link AddressType }
//     *     
//     */
//    public void setAddress(AddressType value) {
//        this.address = value;
//    }

    /**
     * Gets the value of the targetArea property.
     * 
     * @return
     *     possible object is
     *     {@link WhereType }
     *     
     */
    @Override
	public WhereType getTargetArea() {
       return getExtension(RM_TARGETAREA);
    }

    /**
     * Sets the value of the targetArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhereType }
     *     
     */
    @Override
	public WhereType addTargetArea() {
        return addExtension(RM_TARGETAREA);
    }

}
