//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrganisationNameElementList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OrganisationNameElementList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="NameOnly"/>
 *     &lt;enumeration value="TypeOnly"/>
 *     &lt;enumeration value="FullName"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OrganisationNameElementList", namespace = "urn:oasis:names:tc:ciq:xnl:3")
@XmlEnum
public enum OrganisationNameElementList {


    /**
     * "Sakthisoft" in "Sakthisoft Pty. Ltd". "Pty.Ltd" is the legal entity for the organisation name "Sakthisoft"
     * 
     */
    @XmlEnumValue("NameOnly")
    NAME_ONLY("NameOnly"),

    /**
     * "Pty. Ltd" in Sakthisoft Pty.Ltd, where "Sakthisoft" is the name of the organisation.
     * 
     * ""Inc" in ABC Inc, where "ABC" is organisation name
     * 
     */
    @XmlEnumValue("TypeOnly")
    TYPE_ONLY("TypeOnly"),

    /**
     * Full Name of the organisation. e.g. Sakthisoft Pty. Ltd
     * 
     */
    @XmlEnumValue("FullName")
    FULL_NAME("FullName");
    private final String value;

    OrganisationNameElementList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrganisationNameElementList fromValue(String v) {
        for (OrganisationNameElementList c: OrganisationNameElementList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
