//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:ciq:xpil:3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mitre.eren.protocol.edxl_rm;
