//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyIdentifierTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PartyIdentifierTypeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="TaxID"/>
 *     &lt;enumeration value="CompanyID"/>
 *     &lt;enumeration value="NationalID"/>
 *     &lt;enumeration value="RegistrationID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PartyIdentifierTypeList")
@XmlEnum
public enum PartyIdentifierTypeList {

    @XmlEnumValue("TaxID")
    TAX_ID("TaxID"),
    @XmlEnumValue("CompanyID")
    COMPANY_ID("CompanyID"),
    @XmlEnumValue("NationalID")
    NATIONAL_ID("NationalID"),
    @XmlEnumValue("RegistrationID")
    REGISTRATION_ID("RegistrationID");
    private final String value;

    PartyIdentifierTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PartyIdentifierTypeList fromValue(String v) {
        for (PartyIdentifierTypeList c: PartyIdentifierTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
