//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.apache.abdera.model.Element;
import org.apache.abdera.model.ExtensibleElement;


/**
 * Reusable complex type for a party. A party is a person or an organisation
 * 
 * <p>Java class for PartyNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyNameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:ciq:xnl:3}NameLine" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonName" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:oasis:names:tc:ciq:xnl:3}PersonNameType">
 *                 &lt;anyAttribute processContents='lax' namespace='##other'/>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OrganisationName" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:oasis:names:tc:ciq:xnl:3}OrganisationNameType">
 *                 &lt;anyAttribute processContents='lax' namespace='##other'/>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:oasis:names:tc:ciq:ct:3}grLanguageCode"/>
 *       &lt;attGroup ref="{urn:oasis:names:tc:ciq:xnl:3}grNameKey"/>
 *       &lt;attGroup ref="{urn:oasis:names:tc:ciq:ct:3}grValidityDate"/>
 *       &lt;attGroup ref="{urn:oasis:names:tc:ciq:ct:3}grDataQuality"/>
 *       &lt;attribute name="PartyNameID" type="{urn:oasis:names:tc:ciq:ct:3}String" />
 *       &lt;attribute name="PartyNameIDType" type="{urn:oasis:names:tc:ciq:xnl:3}PartyNameIDTypeList" />
 *       &lt;attribute name="ID" type="{urn:oasis:names:tc:ciq:ct:3}String" />
 *       &lt;attribute name="Usage" type="{urn:oasis:names:tc:ciq:xnl:3}PartyNameUsageList" />
 *       &lt;attribute name="Status" type="{urn:oasis:names:tc:ciq:ct:3}StatusList" />
 *       &lt;attribute name="JointNameConnector" type="{urn:oasis:names:tc:ciq:xnl:3}JointNameConnectorList" />
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink1}type"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink1}label"/>
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink1}href"/>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyNameType", namespace = "urn:oasis:names:tc:ciq:xnl:3", propOrder = {
    "nameLine",
    "personName",
    "organisationName"
})
public interface PartyNameType extends Element, ExtensibleElement, EDXLRMConstants {


//    public List<NameLine> getNameLine();
    public List<PersonName> getPersonName();
    public PersonName addPersonName();
    public List<OrganisationName> getOrganisationName();
    public OrganisationName addOrganisationName();
//    public String getPartyNameID();
//    public void setPartyNameID(String value);
//    public String getPartyNameIDType();
//    public void setPartyNameIDType(String value);
//    public String getID();
//    public void setID(String value);
//    public String getUsage();
//    public void setUsage(String value);
//    public String getStatus();
//    public void setStatus(String value);
//    public String getJointNameConnector();
//    public void setJointNameConnector(String value);
//    public String getType();
//    public void setType(String value);
//    public String getLabel();
//    public void setLabel(String value);
//    public String getHref();
//    public void setHref(String value);
//    public String getLanguageCode();
//    public void setLanguageCode(String value);
//    public String getNameKey();
//    public void setNameKey(String value);
//    public String getNameKeyRef();
//    public void setNameKeyRef(String value);
//    public XMLGregorianCalendar getDateValidFrom();
//    public void setDateValidFrom(XMLGregorianCalendar value);
//    public XMLGregorianCalendar getDateValidTo();
//    public void setDateValidTo(XMLGregorianCalendar value);
//    public DataQualityTypeList getDataQualityType();
//    public void setDataQualityType(DataQualityTypeList value);
//    public XMLGregorianCalendar getValidFrom();
//    public void setValidFrom(XMLGregorianCalendar value);
//    public XMLGregorianCalendar getValidTo();
//    public void setValidTo(XMLGregorianCalendar value);
//    public Map<QName, String> getOtherAttributes();


}
