//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostalDeliveryPointTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PostalDeliveryPointTypeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="GPOBox"/>
 *     &lt;enumeration value="POBox"/>
 *     &lt;enumeration value="LockedBag"/>
 *     &lt;enumeration value="MailStop"/>
 *     &lt;enumeration value="PigeonHole"/>
 *     &lt;enumeration value="PrivateBag"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PostalDeliveryPointTypeList", namespace = "urn:oasis:names:tc:ciq:xal:3")
@XmlEnum
public enum PostalDeliveryPointTypeList {

    @XmlEnumValue("GPOBox")
    GPO_BOX("GPOBox"),
    @XmlEnumValue("POBox")
    PO_BOX("POBox"),
    @XmlEnumValue("LockedBag")
    LOCKED_BAG("LockedBag"),
    @XmlEnumValue("MailStop")
    MAIL_STOP("MailStop"),
    @XmlEnumValue("PigeonHole")
    PIGEON_HOLE("PigeonHole"),
    @XmlEnumValue("PrivateBag")
    PRIVATE_BAG("PrivateBag");
    private final String value;

    PostalDeliveryPointTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PostalDeliveryPointTypeList fromValue(String v) {
        for (PostalDeliveryPointTypeList c: PostalDeliveryPointTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
