//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.apache.abdera.model.Element;
import org.apache.abdera.model.ExtensibleElement;


/**
 * <p>Java class for RadioInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RadioInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RadioType" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ValueListType"/>
 *         &lt;element name="RadioChannel" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}RadioChannelType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioInformationType", namespace = "urn:oasis:names:tc:emergency:EDXL:RM:1.0", propOrder = {
    "radioType",
    "radioChannel"
})
public interface RadioInformationType extends Element, ExtensibleElement, EDXLRMConstants {

    public ValueListType getRadioType();
    public ValueListType addRadioType();
    public String getRadioChannel();
    public void setRadioChannel(String value);
}
