//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.abdera.model.Element;
import org.apache.abdera.model.ExtensibleElement;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageIDType"/>
 *         &lt;element name="SentDateTime" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}DateTimeType"/>
 *         &lt;element name="MessageContentType">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageContentTypeType">
 *               &lt;enumeration value="RequestResource"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MessageDescription" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageDescriptionType" minOccurs="0"/>
 *         &lt;element name="OriginatingMessageID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageIDType"/>
 *         &lt;element name="IncidentInformation" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}IncidentInformationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MessageRecall" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageRecallType" minOccurs="0"/>
 *         &lt;element name="Funding" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FundCode" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}FundCodeType" minOccurs="0"/>
 *                   &lt;element name="FundingInfo" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}FundingInfoType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ContactInformation" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ContactInformationType" maxOccurs="unbounded"/>
 *         &lt;element name="ResourceInformation" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResourceInfoElementID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ResourceInfoElementIDType"/>
 *                   &lt;element name="Resource">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ResourceID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ResourceIDType" minOccurs="0"/>
 *                             &lt;element name="Name" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ResourceNameType" minOccurs="0"/>
 *                             &lt;element name="TypeStructure" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ValueListType" minOccurs="0"/>
 *                             &lt;element name="TypeInfo" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}TypeInfoType" minOccurs="0"/>
 *                             &lt;element name="Keyword" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ValueListType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Description" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}DescriptionType" minOccurs="0"/>
 *                             &lt;element name="Credentials" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}CredentialsType" minOccurs="0"/>
 *                             &lt;element name="Certifications" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}CertificationsType" minOccurs="0"/>
 *                             &lt;element name="SpecialRequirements" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}SpecialRequirementsType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AssignmentInformation" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Quantity" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}QuantityType" minOccurs="0"/>
 *                             &lt;element name="Restrictions" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}RestrictionsType" minOccurs="0"/>
 *                             &lt;element name="AnticipatedFunction" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}AnticipatedFunctionType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ScheduleInformation" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ScheduleType">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ScheduleTypeType">
 *                                   &lt;enumeration value="RequestedArrival"/>
 *                                   &lt;enumeration value="RequestedDeparture"/>
 *                                   &lt;enumeration value="EstimatedReturnDeparture"/>
 *                                   &lt;enumeration value="EstimatedReturnArrival"/>
 *                                   &lt;enumeration value="ReportTo"/>
 *                                   &lt;enumeration value="Route"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DateTime" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}DateTimeType" minOccurs="0"/>
 *                             &lt;element name="Location" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}LocationType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageID",
    "sentDateTime",
    "messageContentType",
    "messageDescription",
    "originatingMessageID",
    "incidentInformation",
    "messageRecall",
    "funding",
    "contactInformation",
    "resourceInformation"
})
@XmlRootElement(name = "RequestResource", namespace = "urn:oasis:names:tc:emergency:EDXL:RM:1.0:msg")
public interface RequestResource extends Element, ExtensibleElement, EDXLRMConstants {

// 
//    /**
//     * Gets the value of the messageID property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getMessageID() {
//        return messageID;
//    }
//
//    /**
//     * Sets the value of the messageID property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setMessageID(String value) {
//        this.messageID = value;
//    }
//
//    /**
//     * Gets the value of the sentDateTime property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link XMLGregorianCalendar }
//     *     
//     */
//    public XMLGregorianCalendar getSentDateTime() {
//        return sentDateTime;
//    }
//
//    /**
//     * Sets the value of the sentDateTime property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link XMLGregorianCalendar }
//     *     
//     */
//    public void setSentDateTime(XMLGregorianCalendar value) {
//        this.sentDateTime = value;
//    }
//
//    /**
//     * Gets the value of the messageContentType property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getMessageContentType() {
//        return messageContentType;
//    }
//
//    /**
//     * Sets the value of the messageContentType property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setMessageContentType(String value) {
//        this.messageContentType = value;
//    }
//
//    /**
//     * Gets the value of the messageDescription property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getMessageDescription() {
//        return messageDescription;
//    }
//
//    /**
//     * Sets the value of the messageDescription property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setMessageDescription(String value) {
//        this.messageDescription = value;
//    }
//
//    /**
//     * Gets the value of the originatingMessageID property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getOriginatingMessageID() {
//        return originatingMessageID;
//    }
//
//    /**
//     * Sets the value of the originatingMessageID property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setOriginatingMessageID(String value) {
//        this.originatingMessageID = value;
//    }
//
//    /**
//     * Gets the value of the incidentInformation property.
//     * 
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the incidentInformation property.
//     * 
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getIncidentInformation().add(newItem);
//     * </pre>
//     * 
//     * 
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link IncidentInformationType }
//     * 
//     * 
//     */
//    public List<IncidentInformationType> getIncidentInformation() {
//        if (incidentInformation == null) {
//            incidentInformation = new ArrayList<IncidentInformationType>();
//        }
//        return this.incidentInformation;
//    }
//
//    /**
//     * Gets the value of the messageRecall property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link MessageRecallType }
//     *     
//     */
//    public MessageRecallType getMessageRecall() {
//        return messageRecall;
//    }
//
//    /**
//     * Sets the value of the messageRecall property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link MessageRecallType }
//     *     
//     */
//    public void setMessageRecall(MessageRecallType value) {
//        this.messageRecall = value;
//    }
//
//    /**
//     * Gets the value of the funding property.
//     * 
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the funding property.
//     * 
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getFunding().add(newItem);
//     * </pre>
//     * 
//     * 
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link RequestResource.Funding }
//     * 
//     * 
//     */
//    public List<RequestResource.Funding> getFunding() {
//        if (funding == null) {
//            funding = new ArrayList<RequestResource.Funding>();
//        }
//        return this.funding;
//    }
//
//    /**
//     * Gets the value of the contactInformation property.
//     * 
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the contactInformation property.
//     * 
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getContactInformation().add(newItem);
//     * </pre>
//     * 
//     * 
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link ContactInformationType }
//     * 
//     * 
//     */
//    public List<ContactInformationType> getContactInformation() {
//        if (contactInformation == null) {
//            contactInformation = new ArrayList<ContactInformationType>();
//        }
//        return this.contactInformation;
//    }
//
//    /**
//     * Gets the value of the resourceInformation property.
//     * 
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the resourceInformation property.
//     * 
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getResourceInformation().add(newItem);
//     * </pre>
//     * 
//     * 
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link RequestResource.ResourceInformation }
//     * 
//     * 
//     */
//    public List<RequestResource.ResourceInformation> getResourceInformation() {
//        if (resourceInformation == null) {
//            resourceInformation = new ArrayList<RequestResource.ResourceInformation>();
//        }
//        return this.resourceInformation;
//    }



}
