//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:13:51 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

import org.apache.abdera.factory.Factory;
import org.apache.abdera.model.Element;
import org.mitre.javautil.logging.LoggingUtils;
import org.opencare.lib.model.BaseWrapper;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageIDType"/>
 *         &lt;element name="SentDateTime" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}DateTimeType"/>
 *         &lt;element name="MessageContentType">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageContentTypeType">
 *               &lt;enumeration value="ReportResourceDeploymentStatus"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MessageDescription" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageDescriptionType" minOccurs="0"/>
 *         &lt;element name="OriginatingMessageID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageIDType"/>
 *         &lt;element name="PrecedingMessageID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageIDType" minOccurs="0"/>
 *         &lt;element name="IncidentInformation" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}IncidentInformationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MessageRecall" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}MessageRecallType" minOccurs="0"/>
 *         &lt;element name="Funding" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}FundingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ContactInformation" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ContactInformationType" maxOccurs="unbounded"/>
 *         &lt;element name="ResourceInformation" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResourceInfoElementID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ResourceInfoElementIDType"/>
 *                   &lt;element name="ResponseInformation" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ResponseInformationType" minOccurs="0"/>
 *                   &lt;element name="Resource" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ResourceID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ResourceIDType" minOccurs="0"/>
 *                             &lt;element name="Name" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ResourceNameType" minOccurs="0"/>
 *                             &lt;element name="TypeStructure" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ValueListType" minOccurs="0"/>
 *                             &lt;element name="TypeInfo" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}TypeInfoType" minOccurs="0"/>
 *                             &lt;element name="Keyword" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ValueListType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Description" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}DescriptionType" minOccurs="0"/>
 *                             &lt;element name="Credentials" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}CredentialsType" minOccurs="0"/>
 *                             &lt;element name="Certifications" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}CertificationsType" minOccurs="0"/>
 *                             &lt;element name="SpecialRequirements" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}SpecialRequirementsType" minOccurs="0"/>
 *                             &lt;element name="ResponsibleParty" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ContactInformationType" minOccurs="0"/>
 *                             &lt;element name="OwnershipInformation" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}OwnershipInformationType" minOccurs="0"/>
 *                             &lt;element name="ResourceStatus" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="InventoryRefreshDateTime" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}DateTimeType" minOccurs="0"/>
 *                                       &lt;element name="DeploymentStatus" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ValueListType" minOccurs="0"/>
 *                                       &lt;element name="Availability" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}AvailabilityType" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AssignmentInformation" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Quantity" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}QuantityType" minOccurs="0"/>
 *                             &lt;element name="Restrictions" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}RestrictionsType" minOccurs="0"/>
 *                             &lt;element name="AnticipatedFunction" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}AnticipatedFunctionType" minOccurs="0"/>
 *                             &lt;element name="PriceQuote" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}PriceQuoteType" minOccurs="0"/>
 *                             &lt;element name="OrderID" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}OrderIDType" minOccurs="0"/>
 *                             &lt;element name="AssignmentInstructions" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}AssignmentInstructionsType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ScheduleInformation" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ScheduleType">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}ScheduleTypeType">
 *                                   &lt;enumeration value="RequestedArrival"/>
 *                                   &lt;enumeration value="EstimatedArrival"/>
 *                                   &lt;enumeration value="ActualArrival"/>
 *                                   &lt;enumeration value="RequestedDeparture"/>
 *                                   &lt;enumeration value="EstimatedDeparture"/>
 *                                   &lt;enumeration value="ActualDeparture"/>
 *                                   &lt;enumeration value="RequestedReturnDeparture"/>
 *                                   &lt;enumeration value="EstimatedReturnDeparture"/>
 *                                   &lt;enumeration value="ActualReturnDeparture"/>
 *                                   &lt;enumeration value="RequestedReturnArrival"/>
 *                                   &lt;enumeration value="EstimatedReturnArrival"/>
 *                                   &lt;enumeration value="ActualReturnArrival"/>
 *                                   &lt;enumeration value="BeginAvailable"/>
 *                                   &lt;enumeration value="EndAvailable"/>
 *                                   &lt;enumeration value="Committed"/>
 *                                   &lt;enumeration value="Current"/>
 *                                   &lt;enumeration value="ReportTo"/>
 *                                   &lt;enumeration value="Route"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DateTime" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}DateTimeType" minOccurs="0"/>
 *                             &lt;element name="Location" type="{urn:oasis:names:tc:emergency:EDXL:RM:1.0}LocationType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageID",
    "sentDateTime",
    "messageContentType",
    "messageDescription",
    "originatingMessageID",
    "precedingMessageID",
    "incidentInformation",
    "messageRecall",
    "funding",
    "contactInformation",
    "resourceInformation"
})
public abstract class ResourceMessageWrapper extends BaseWrapper implements ResourceMessage {

  private static Logger log = LoggingUtils.getLogger(ResourceMessageWrapper.class);
    

    public ResourceMessageWrapper(Element internal) {
    super(internal);
    // TODO Auto-generated constructor stub
  }

    

    public ResourceMessageWrapper(Factory factory, QName qname) {
      super(factory, qname);
      // TODO Auto-generated constructor stub
    }


    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getMessageID() {
      return getSimpleExtension(RM_MESSAGEID);
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setMessageID(String value) {
      setElementText(RM_MESSAGEID, value);
    }

    /**
     * Gets the value of the sentDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Override
	public XMLGregorianCalendar getSentDateTime() {
      String timestring = getSimpleExtension(RM_SENTDATETIME);
      return ERENDatatypeFactory.factory.newXMLGregorianCalendar(timestring);
    }

    /**
     * Sets the value of the sentDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Override
	public void setSentDateTime(XMLGregorianCalendar value) {
      setElementText(RM_SENTDATETIME, value.toXMLFormat());
    }
    
    /**
     * Convenience method with string argument
     */
    @Override
	public void setSentDateTime(String value) { 
      setElementText(RM_SENTDATETIME, value);
    }

    /**
     * Gets the value of the messageContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getMessageContentType() {
      return getSimpleExtension(RM_MESSAGECONTENTTYPE);
    }

    /**
     * Sets the value of the messageContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setMessageContentType(String value) {
        setElementText(RM_MESSAGECONTENTTYPE,value);
    }

    /**
     * Gets the value of the messageDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getMessageDescription() {
        return getSimpleExtension(RM_MESSAGEDESCRIPTION);
    }

    /**
     * Sets the value of the messageDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setMessageDescription(String value) {
        setElementText(RM_MESSAGEDESCRIPTION,value);
    }

    /**
     * Gets the value of the originatingMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getOriginatingMessageID() {
        return getSimpleExtension(RM_ORIGINATINGMESSAGEID);
    }

    /**
     * Sets the value of the originatingMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setOriginatingMessageID(String value) {
        setElementText(RM_ORIGINATINGMESSAGEID,value);
    }

    /**
     * Gets the value of the precedingMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getPrecedingMessageID() {
      return getSimpleExtension(RM_PRECEDINGMESSAGEID);
    }

    /**
     * Sets the value of the precedingMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setPrecedingMessageID(String value) {
      setElementText(RM_PRECEDINGMESSAGEID,value);
    }

    /**
     * Gets the value of the incidentInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentInformationType }
     * 
     * 
     */
    @Override
	public List<IncidentInformationType> getIncidentInformation() {
      List<IncidentInformationType> info = getExtensions(RM_INCIDENTINFORMATION);
      return info;
    }
    
    @Override
	public IncidentInformationType addIncidentInformation () { 
      return addExtension(RM_INCIDENTINFORMATION);
    }

    /**
     * Convenience method
     *
     */
    @Override
	public void addIncident (String incident) { 
      IncidentInformationType ii = addIncidentInformation();
      ii.setIncidentDescription(incident);
    }
    
    /**
     * Gets the value of the messageRecall property.
     * 
     * @return
     *     possible object is
     *     {@link MessageRecallType }
     *     
     */
    @Override
	public MessageRecallType getMessageRecall() {
      MessageRecallType recall = getExtension(RM_MESSAGERECALL);
      return recall;
    }

    /**
     * Sets the value of the messageRecall property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageRecallType }
     *     
     */
    @Override
	public MessageRecallType addMessageRecall() {
        return addExtension(RM_MESSAGERECALL);
    }

    /**
     * Gets the value of the funding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the funding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFunding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FundingType }
     * 
     * 
     */
    @Override
	public List<FundingType> getFunding() {
        return getExtensions(RM_FUNDING);
    }
    
    @Override
	public FundingType addFunding () { 
      return addExtension(RM_FUNDING);
    }

    /**
     * Gets the value of the contactInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactInformationType }
     * 
     * 
     */
    @Override
	public List<ContactInformationType> getContactInformation() {
        
        return getExtensions(RM_CONTACTINFORMATION);
    }

    
    @Override
	public ContactInformationType addContactInformation () { 
      return addExtension(RM_CONTACTINFORMATION);
    }
    
    /**
     * Gets the value of the resourceInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportResourceDeploymentStatusWrapper.ResourceInformation }
     * 
     * 
     */
    @Override
	public List<ResourceInformation> getResourceInformation() {
      return getExtensions(RM_RESOURCEINFORMATION);
    }

    
    @Override
	public ResourceInformation addResourceInformation () { 
      return addExtension(RM_RESOURCEINFORMATION);
    }
    
    public boolean hasResourceId (String id) { 
      for (ResourceInformation ri : getResourceInformation()) { 
        try { 
          if (ri.getResource().getResourceID().equals(id)) { 
            return true;
          }
        } catch (Exception e) { }
      }
      return false;
    }
    
    public boolean hasResourceType (String type) { 
      for (ResourceInformation ri : getResourceInformation()) { 
        for (String value : ri.getResource().getTypeStructure().getValue()) { 
          if (value.equalsIgnoreCase(type)) { 
            return true;
          }
        }
      }
      return false;
    }
    
    /**
     * Returns the ID of the first resource
     * @return
     */
    public String getResourceID () { 
      List<ResourceInformation> ri =  getResourceInformation(); 
      return ri.get(0).getResource().getResourceID();
    }

    public List<String> getResourceTypes () { 
      List<ResourceInformation> ri = getResourceInformation();
      return ri.get(0).getResource().getTypeStructure().getValue();
    }
    
    /** 
     * Get the type of resource that is the subject of this message 
     * (assume only one resource type)
     */
    public String getResourceType () { 
      if (getResourceInformation().isEmpty()) return null;
      ResourceInformation ri = getResourceInformation().get(0);
      return ri.getResource().getTypeStructure().getValue().get(0);
    }

    /** 
     * Get the name of resource that is the subject of this message 
     * (assume only one resource)
     */
    public String getResourceName () { 
      if (getResourceInformation().isEmpty()) return null;
      ResourceInformation ri = getResourceInformation().get(0);
      return ri.getResource().getName();
    }

    public String getResourceTypeDescription() { 
      return ResourceTypes.valueOf(getResourceType()).getDescription();
    }

    public List<Resource> getResourcesByType (String type) { 
      List<Resource> result = new ArrayList<Resource>();
      for (ResourceInformation ri : getResourceInformation() ) { 
        if (ri.getResource().getTypeStructure().getValue().equals(type)) { 
          result.add(ri.getResource());
        }
      }
      return result;
    }
    
    /** 
     * Get the location where the resource is being assigned to
     */
    public String getResourceLocationByDescription () {
      if (getResourceInformation().isEmpty()) return null;
      ResourceInformation ri = getResourceInformation().get(0);
      if (ri.getScheduleInformation().isEmpty()) return null;
      ScheduleInformation si = ri.getScheduleInformation().get(0);
      if (si.getLocation() == null) return null;
      return si.getLocation().getLocationDescription();
    }
    
    
    /** 
     * 
     * Convenience method. Get the description of the requester
     */
    public String getContact (String roleType) { 
      List<ContactInformationType> cis = getContactInformation();
      for (ContactInformationType ci : cis) { 
        if (ci.getContactRole() == ContactRoleType.fromValue(roleType)) { 
          return ci.getContactDescription();
        }
      }
      return null;
    }
    
}
