//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.26 at 12:27:28 PM EDT 
//


package org.mitre.eren.protocol.edxl_rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScheduleTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScheduleTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RequestedArrival"/>
 *     &lt;enumeration value="EstimatedArrival"/>
 *     &lt;enumeration value="ActualArrival"/>
 *     &lt;enumeration value="RequestedDeparture"/>
 *     &lt;enumeration value="EstimatedDeparture"/>
 *     &lt;enumeration value="ActualDeparture"/>
 *     &lt;enumeration value="EstimatedReturnDeparture"/>
 *     &lt;enumeration value="EstimatedReturnArrival"/>
 *     &lt;enumeration value="ActualReturnArrival"/>
 *     &lt;enumeration value="RequestedReturnDeparture"/>
 *     &lt;enumeration value="RequestedReturnArrival"/>
 *     &lt;enumeration value="ActualReturnDeparture"/>
 *     &lt;enumeration value="BeginAvailable"/>
 *     &lt;enumeration value="EndAvailable"/>
 *     &lt;enumeration value="Committed"/>
 *     &lt;enumeration value="Current"/>
 *     &lt;enumeration value="ReportTo"/>
 *     &lt;enumeration value="Route"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScheduleTypeType", namespace = "urn:oasis:names:tc:emergency:EDXL:RM:1.0")
@XmlEnum
public enum ScheduleTypeType {

    @XmlEnumValue("RequestedArrival")
    REQUESTED_ARRIVAL("RequestedArrival"),
    @XmlEnumValue("EstimatedArrival")
    ESTIMATED_ARRIVAL("EstimatedArrival"),
    @XmlEnumValue("ActualArrival")
    ACTUAL_ARRIVAL("ActualArrival"),
    @XmlEnumValue("RequestedDeparture")
    REQUESTED_DEPARTURE("RequestedDeparture"),
    @XmlEnumValue("EstimatedDeparture")
    ESTIMATED_DEPARTURE("EstimatedDeparture"),
    @XmlEnumValue("ActualDeparture")
    ACTUAL_DEPARTURE("ActualDeparture"),
    @XmlEnumValue("EstimatedReturnDeparture")
    ESTIMATED_RETURN_DEPARTURE("EstimatedReturnDeparture"),
    @XmlEnumValue("EstimatedReturnArrival")
    ESTIMATED_RETURN_ARRIVAL("EstimatedReturnArrival"),
    @XmlEnumValue("ActualReturnArrival")
    ACTUAL_RETURN_ARRIVAL("ActualReturnArrival"),
    @XmlEnumValue("RequestedReturnDeparture")
    REQUESTED_RETURN_DEPARTURE("RequestedReturnDeparture"),
    @XmlEnumValue("RequestedReturnArrival")
    REQUESTED_RETURN_ARRIVAL("RequestedReturnArrival"),
    @XmlEnumValue("ActualReturnDeparture")
    ACTUAL_RETURN_DEPARTURE("ActualReturnDeparture"),
    @XmlEnumValue("BeginAvailable")
    BEGIN_AVAILABLE("BeginAvailable"),
    @XmlEnumValue("EndAvailable")
    END_AVAILABLE("EndAvailable"),
    @XmlEnumValue("Committed")
    COMMITTED("Committed"),
    @XmlEnumValue("Current")
    CURRENT("Current"),
    @XmlEnumValue("ReportTo")
    REPORT_TO("ReportTo"),
    @XmlEnumValue("Route")
    ROUTE("Route");
    private final String value;

    ScheduleTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScheduleTypeType fromValue(String v) {
        for (ScheduleTypeType c: ScheduleTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
